version = 0.1

[default.global.parameters]
stack_name = "salesops-ai-dev"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "salesops-ai-dev"
parameter_overrides = "StageName=\"dev\""
image_repositories = []
